import './style.css';
import './overrides.css';
import hero from './assets/blueprint-hero.webp';

type Route = 'home' | 'demo' | 'privacy' | 'terms' | 'not-found';
const app = document.querySelector<HTMLDivElement>('#app')!;
const billing = 'https://api.sociobot.in/api/v1/products/android-compat-scout';

const shell = (content: string) => `
<header class="topbar"><a class="wordmark" href="/" data-route>ANDROID<br><strong>COMPAT SCOUT</strong></a><nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="#install">Install</a><a href="/privacy" data-route>Privacy</a></nav></header>
<div class="route-note" aria-live="polite"></div><main id="main" tabindex="-1">${content}</main>
<footer><p>Private evidence for Android setup changes.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v0.1.0</p></footer>`;
const terminal = `<div class="terminal" aria-label="Terminal recording of the sample report"><p><span>$</span> compat-scout demo</p><p>Demo report written to /tmp/compat-scout-demo</p><p>Found 6 compatibility signals.</p><p class="warn">[Permission] ACCESS FINE LOCATION permission changed</p><p class="fault">[Missing component] wireless bridge is no longer installed</p><p><span>$</span> cat /tmp/compat-scout-demo/compat-report.json</p></div>`;

const home = () => shell(`
<section class="hero"><div class="hero-copy"><p class="eyebrow">LOCAL COMPATIBILITY INSPECTION / 01</p><h1>Find what broke your Android setup</h1><p class="lede">For custom-phone and dongle owners after an update, it turns scattered device facts into a clear report.</p><div class="hero-actions"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>See a private upgrade report first.</span></div><ul class="facts"><li>Runs on your computer</li><li>Redacts serials and accounts</li><li>$12 one-time Pro license</li></ul></div><figure class="hero-art"><img src="${hero}" width="1536" height="1024" fetchpriority="high" alt="Blueprint illustration of a phone, USB cable, and vehicle dongle used for compatibility inspection."><figcaption>Trace the change. Keep the evidence.</figcaption></figure></section>
<section class="live-sheet" aria-labelledby="report-title"><div><p class="eyebrow">SAMPLE REPORT / ANDROID 14 → 15</p><h2 id="report-title">Sort changes by what to check</h2><p>A report marks the update, permission, connection, and missing app separately.</p></div>${terminal}</section>
<section class="method" aria-labelledby="how-title"><p class="eyebrow">WORKFLOW / 02</p><h2 id="how-title">Take evidence before guessing</h2><ol><li><strong>Capture a snapshot.</strong><span>Connect your phone and accept its USB-debugging prompt.</span></li><li><strong>Declare the setup.</strong><span>List the local app, permissions, and device roles it needs.</span></li><li><strong>Compare after changes.</strong><span>Save a report that names each meaningful difference.</span></li></ol></section>
<section class="boundary"><h2>It reports facts. It does not change your phone.</h2><p>Compat Scout never roots a device, bypasses Android Auto restrictions, changes installed apps, or encourages driving interaction.</p><p>Snapshots omit serial numbers, accounts, Wi-Fi names, and MAC addresses. Keep reports where you trust them.</p></section>
<section id="install" class="install" aria-labelledby="install-title"><div><p class="eyebrow">INSTALL / 03</p><h2 id="install-title">Install the command-line tool</h2><p id="download-state">Downloads are being published. You can build from source today.</p></div><div><pre><code>cargo install android-compat-scout
compat-scout snapshot --out before.json
compat-scout compare before.json after.json</code></pre><p><a href="/install.sh">Linux / macOS installer</a> · <a href="/install.ps1">Windows installer</a> · <a href="https://github.com/B-Divyesh/sf-android-compat-scout/releases" target="_blank" rel="noreferrer">Release page</a></p></div></section>
<section class="paid" aria-labelledby="pro-title"><p class="eyebrow">PRO / ONE-TIME LICENSE</p><h2 id="pro-title">Save declared setup checks for $12</h2><p>The free tool captures snapshots and exports reports. Pro saves multiple setup requirement files and keeps an inspection index on this computer.</p><p><a class="button primary" href="${billing}/checkout">Buy Pro for $12</a></p><form id="license-form"><label for="license">Have a license? Paste it here.</label><div><input id="license" name="license" autocomplete="off"><button type="submit">Verify license</button></div><p id="license-result" aria-live="polite"></p></form></section>`);

const demo = () => shell(`<aside class="demo-banner"><strong>Demo — sample data, nothing is saved</strong><button id="reset-demo">Reset demo</button><a href="/">Start for real</a></aside><section class="demo-page"><p class="eyebrow">SANDBOX / SAMPLE UPGRADE</p><h1>See an Android upgrade report</h1><p class="lede">This sample compares an invented Android 14 setup with its Android 15 snapshot.</p><div class="demo-grid"><article><h2>Compatibility signals</h2><ul class="findings"><li><b>OS version</b><span>Android changed from 14 to 15</span><em>Check app support notes.</em></li><li class="blocking"><b>Permission</b><span>ACCESS FINE LOCATION changed</span><em>Review the trusted app's permission page.</em></li><li class="blocking"><b>Missing component</b><span>Wireless bridge is no longer installed</span><em>Restore it from a trusted backup.</em></li></ul></article>${terminal}</div><h2>Run the same bundled demo</h2><pre><code>compat-scout demo
# writes compat-report.json in a temporary folder</code></pre></section>`);
const legal = (kind: 'privacy' | 'terms') => shell(kind === 'privacy' ? `<section class="legal"><h1>Privacy for Android Compat Scout</h1><h2>Your snapshots stay on your computer</h2><p>The command-line tool reads device facts only after you enable USB debugging and approve the phone prompt. It does not send snapshots to us.</p><h2>What a snapshot omits</h2><p>Exports exclude serial numbers, account information, Wi-Fi names, and MAC addresses. You choose where report files are stored.</p><h2>Optional license check</h2><p>If you paste a Pro license, the site sends that token to Sociobot to verify it. The site stores the license only in this browser.</p></section>` : `<section class="legal"><h1>Terms for Android Compat Scout</h1><h2>Use it for diagnosis</h2><p>Compat Scout compares information you are allowed to inspect. It does not root devices, bypass restrictions, or modify apps.</p><h2>Keep safe</h2><p>Do not use the tool while driving. Follow local laws and only connect devices you own or manage.</p><h2>Pro license</h2><p>Pro is a $12 one-time license. Sociobot and Dodo are the merchant of record. A refunded license is revoked.</p></section>`);
const notFound = () => shell(`<section class="not-found"><p class="eyebrow">SHEET NOT FOUND</p><h1>This inspection page is missing</h1><p>Return to the Compat Scout overview to inspect a sample report.</p><a class="button primary" href="/" data-route>Go to overview</a></section>`);

function route(): Route { const p = location.pathname.replace(/\/$/, '') || '/'; return p === '/' ? 'home' : p === '/demo' ? 'demo' : p === '/privacy' ? 'privacy' : p === '/terms' ? 'terms' : 'not-found'; }
function render() { const current = route(); app.innerHTML = current === 'home' ? home() : current === 'demo' ? demo() : current === 'privacy' ? legal('privacy') : current === 'terms' ? legal('terms') : notFound(); const titles: Record<Route, string> = { home: 'Android Compat Scout — Find Android setup regressions', demo: 'Demo — Android Compat Scout', privacy: 'Privacy — Android Compat Scout', terms: 'Terms — Android Compat Scout', 'not-found': 'Page not found — Android Compat Scout' }; document.title = titles[current]; document.querySelector('.route-note')!.textContent = document.title; bind(); requestAnimationFrame(() => document.querySelector<HTMLElement>('h1')?.focus({ preventScroll: true })); }
function bind() { document.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); history.pushState({}, '', a.href); render(); })); document.querySelector('#reset-demo')?.addEventListener('click', () => { sessionStorage.removeItem('demo:compat-scout'); render(); }); void loadDownload(); document.querySelector<HTMLFormElement>('#license-form')?.addEventListener('submit', async e => { e.preventDefault(); const token = new FormData(e.currentTarget).get('license')?.toString().trim(); const out = document.querySelector('#license-result')!; if (!token) { out.textContent = 'Paste a license token first.'; return; } localStorage.setItem('sb_license:android-compat-scout', token); out.textContent = 'Checking your license…'; try { const r = await fetch(`${billing}/verify?license=${encodeURIComponent(token)}`); const x = await r.json(); out.textContent = x.valid ? 'License active. Pro is available.' : 'This license is not active. Check the token or buy Pro.'; } catch { out.textContent = 'Could not verify now. Your saved license will be checked later.'; } }); }
async function loadDownload() { const target = document.querySelector('#download-state'); if (!target) return; const cacheKey = 'compat-scout:release'; let release: { assets?: { name: string; browser_download_url: string }[] } | undefined; try { const cached = JSON.parse(localStorage.getItem(cacheKey) || 'null'); if (cached?.until > Date.now()) release = cached.release; if (!release) { const response = await fetch('https://api.github.com/repos/B-Divyesh/sf-android-compat-scout/releases/latest'); if (!response.ok) return; release = await response.json(); localStorage.setItem(cacheKey, JSON.stringify({ until: Date.now() + 3600000, release })); } const windows = navigator.userAgent.includes('Windows'); const mac = /Macintosh|Mac OS/.test(navigator.userAgent); const needle = windows ? 'windows' : mac ? 'apple-darwin' : 'linux'; const asset = release.assets?.find(a => a.name.includes(needle)); if (asset) target.innerHTML = `<a href="${asset.browser_download_url}">Download for this computer</a> · verified checksum included`; } catch { /* Offline and rate-limited states keep the calm default. */ } }
addEventListener('popstate', render); render();
